baseURL = "https://mollywangup.com/"
title = "Molly's Blog"
theme = "zzo"

defaultContentLanguage = "zh"
defaultContentLanguageInSubdir = false # disable redirect 'root/' to 'root/en/'
hasCJKLanguage = true

summaryLength = 70
buildFuture = true

copyright = "©{year}, All content is licensed under <a target='_blank' rel='external noopener' href='https://creativecommons.org/licenses/by-nc/4.0/'>CC BY-NC 4.0</a>."
timeout = 10000
enableEmoji = true
paginate = 13
rssLimit = 100

enableGitInfo = false
# googleAnalytics = "G-BGX5B906J4"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      hardWraps = true
      unsafe = true
      xHTML = true
  [markup.highlight]
    codeFences = true
    lineNos = true
    lineNumbersInTable = true
    noClasses = false
  [markup.tableOfContents]
    endLevel = 4
    ordered = false
    startLevel = 2

[outputs]
  home = ["HTML", "RSS", "SearchIndex"]
  section = ["HTML", "RSS", "SearchIndex"]
  # taxonomyTerm = ["HTML", "RSS", "SearchIndex"]
  taxonomy = ["HTML", "RSS", "SearchIndex"]

[outputFormats]
  [outputFormats.SearchIndex]
    mediaType = "application/json"
    baseName = "index"
    isPlainText = true
    notAlternative = true

[taxonomies]
  category = "categories"
  tag = "tags"
  series = "series"
